<template>
  <article class="container py-4" itemscope itemtype="https://schema.org/VideoGame">
    <Breadcrumb :items="breadcrumbItems" />

    <header class="mb-4">
      <h1 class="mb-2" itemprop="name">{{ game.title }}</h1>
      <p class="text-muted lead" itemprop="description">{{ game.description }}</p>
      <div class="mb-3">
        <span v-for="category in game.categories" :key="category" class="badge bg-success me-2" itemprop="genre">
          {{ category }}
        </span>
      </div>
    </header>

    <section class="game-section" aria-label="Game Area">
      <div class="game-container">
        <div class="controls">
          <select id="levelSelect" class="level-select" onchange="changeLevel()">
            <option value="1">3x3 (Easy)</option>
            <option value="2">4x4 (Medium)</option>
            <option value="3" selected>5x5 (Normal)</option>
            <option value="4">6x6 (Hard)</option>
            <option value="5">7x7 (Expert)</option>
          </select>
          <button onclick="newGame()">New Game</button>
        </div>

        <div class="stats">
          <div>Moves: <span id="moveCount">0</span></div>
          <div>Lights On: <span id="lightsOn">0</span></div>
          <div>Best: <span id="bestScore">-</span></div>
        </div>

        <div id="board"></div>
        <div id="message" class="message"></div>

        <p class="instructions">
          Click a light to toggle it and its neighbors. Turn off all lights to win!
        </p>
      </div>
    </section>

    <GameFaqs :faqs="game.faqs" />
    <RelatedGames :currentSlug="game.slug" :categories="game.categories" />

    <meta itemprop="url" :content="`https://games.muthu.co/posts/${game.slug}/`">
    <meta itemprop="image" :content="`https://games.muthu.co/posts/${game.slug}/thumbnail.png`">
    <meta itemprop="applicationCategory" content="Game">
    <meta itemprop="operatingSystem" content="Web Browser">
    <span itemprop="offers" itemscope itemtype="https://schema.org/Offer" style="display:none">
      <meta itemprop="price" content="0">
      <meta itemprop="priceCurrency" content="USD">
    </span>
  </article>
</template>

<script setup>
import { useGameLoader } from '../../composables/useGameLoader.js'
import { useGameSeo } from '../../composables/useGameSeo.js'
import Breadcrumb from '../../components/Breadcrumb.vue'
import GameFaqs from '../../components/GameFaqs.vue'
import RelatedGames from '../../components/RelatedGames.vue'

const game = {
  slug: 'lights-out',
  title: 'Lights Out Puzzle - Turn Off All Lights',
  shortTitle: 'Lights Out',
  description: 'Toggle lights to turn them all off. Clicking a light switches it and adjacent lights. A classic logic puzzle with multiple grid sizes.',
  metaDescription: 'Play Lights Out puzzle online free. Click lights to toggle them and their neighbors. Turn off all lights to win this classic logic puzzle game.',
  thumbnail: 'thumbnail.png',
  categories: ['Puzzles', 'Logic Games'],
  keywords: ['lights out', 'logic puzzle', 'toggle puzzle', 'brain teaser', 'puzzle game', 'light puzzle'],
  initCode: 'newGame();',
  faqs: [
    {
      question: 'How do you play Lights Out?',
      answer: 'Click on any light to toggle it on or off. When you click a light, it also toggles the lights directly above, below, left, and right of it. Your goal is to turn off all the lights on the board.'
    },
    {
      question: 'Is every Lights Out puzzle solvable?',
      answer: 'Yes! Every puzzle in this game is guaranteed to be solvable because puzzles are generated by making random valid moves from a solved state. This ensures there is always a solution.'
    },
    {
      question: 'What is the best strategy for Lights Out?',
      answer: 'A common strategy is to work row by row from top to bottom. Turn off all lights in the top row by clicking lights in the row below. Repeat until you reach the bottom row, then use the solution pattern for the remaining lights.'
    }
  ]
}

const breadcrumbItems = [
  { name: 'Home', path: '/' },
  { name: 'Games', path: '/' },
  { name: game.shortTitle || game.title, path: `/posts/${game.slug}/` }
]

useGameLoader(game.slug, game.initCode)
useGameSeo(game)
</script>

<style scoped>
h1 { font-weight: 400; }
.game-section { min-height: 400px; }
</style>
