project:
  type: website

website:
  title: "Javascript Games"
  reader-mode: false
  open-graph: true
  page-navigation: true
  page-footer: "Copyright 2025, Muthukrishnan" 
  google-analytics: 
    tracking-id: ''
  site-url: 'https://games.muthu.co'
  site-path: '/'
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/muthuspark
      - icon: twitter
        href: https://twitter.com/krimuthu
format:
  html:
    theme: litera
    css: styles.css
    lang: en
    toc: true
    image: false
    include-before-body:
    - text: |
        <link rel="stylesheet" href="/posts/global.css"></link>
        <script type="text/javascript" src="/posts/global.js"></script>
    mermaid:
      theme: neutral


